### ISSUE TITLE
Multiple identical todo changes

### ISSUE THREAD

**Issue by Ekleog** [Ekleog/todiff#13]
From:
```
hello
hello
```
To:
```
helloa
hellob
```

The diff is:
```
Deleted tasks
-------------

 → hello

Changed tasks
-------------

 → hello
    → Changed subject ‘helloa’
    → Copied and changed subject ‘hellob’
```

It would be nice if it was detected that each task was changed, instead of one deleted and one copied.

**Comment by Ekleog** [comment]
Same behaviour happens with multiple identical TODOs that are completed, most likely for the same reason: the matching algorithm doesn't deprioritize already-matched TODOs.

**Comment by Nadrieril** [comment]
This was fixed in https://github.com/Ekleog/todiff/commit/34350fe69742cde91ae61ec918a4990cb95a4139 , now merged

**Comment by Ekleog** [comment]
Indeed, thanks!
