### ISSUE TITLE
Handle new tasks already completed

### ISSUE THREAD

**Issue by vberger** [Ekleog/todiff#7]
If a task is added then completed between the two diffed files, it appears in the "New tasks" category, and is simply dumped with its `x AAA-MM-DD` completion prefix.

Probably it should instead be displayed in the "completed tasks" section ?

**Comment by Ekleog** [comment]
Hmm, your question raises an interesting issue. I don't think new-but-completed tasks should go in the “Changed tasks” section, under which the “Completed tasks” section currently is.

But, as you say, having a “Completed tasks” section would completely make sense. So I'm wondering a bit about the user interface, and currently am thinking of this:
```
New tasks:
 → [...]

Recurred tasks:
 → [...]
    → Completed on [...]
    → Recurred [(strict)]

Completed tasks:
 → [... including new-and-completed tasks]
    → [Created]
    → Completed on [...]

Postponed tasks:
 → [...]
    → Postponed [(strict)] by [...] days

Changed tasks:
 → [...]
    → [...]
```

What do you think about it?

cc @Nadrieril in case you have an idea, as I seem to remember you started reflexion over overhauling the output.

**Comment by vberger** [comment]
Well, we could argue that "recurred" tasks are legitimately a subgroup of "completed" tasks, and "postponed" tasks a subgroup of "changed" task, maybe?

**Comment by Nadrieril** [comment]
I like the idea of having a separate list for completed tasks. I probably have a branch somewhere that started that for deleted tasks, but I didn't finish it

**Comment by Ekleog** [comment]
Hmm, so something like:
```
New tasks:
 → [...]

Completed tasks:
 → [recurred tasks...]
    → Completed on [...]
    → Recurred [(strict)]

 → [completed tasks... including new-and-completed tasks]
    → [Created]
    → Completed on [...]

Changed tasks:
 → [postponed tasks...]
    → Postponed [(strict)] by [...] days

 → [other changed tasks...]
    → [...]
```

Does that look good to you?

**Comment by Ekleog** [comment]
I've just pushed dfb8abc41d986cdf74d1fa45be1c1e28bfa8c670 (branch `new-output`) that should do this (while keeping the old output for some testing time).

Could you test and check this looks good to you? :)

**Comment by Ekleog** [comment]
Done in https://github.com/Ekleog/todiff/commit/55d320d4a2d1d25dd1bdea85cc17ffdceda6717b
